### ISSUE TITLE
Trade mail confirmation

### ISSUE THREAD

**Issue by Ax6** [seishun/node-steam-trade#53]
So, now there is mail confirmation also for manual trade, I'm not sure what and if something has to be changed, although completing a trade with mail verification enabled, for example, now emits an undefined result.

**Comment by alvinl** [comment]
Looks like there's a new `trade_status` code for verified trades (6). The reason it's emitting `undefined` is because it needs to be added [here](https://github.com/seishun/node-steam-trade/blob/master/index.js#L122). Seems like verified trades now rely on the trade offers system to put the trade "on hold" while the user confirms the trade via email (see [this](https://cloudup.com/iy6ad55FiWW)). With that being said, the "fix" would be to poll your incoming trade offers if your trade ends with that status code 6 and act on that.

**Comment by pmk010** [comment]
Another option would be to disable mail confirmation of manual trades? You can do that by navigating to Inventory > More > Inventory Privacy Settings and set "Confirmation of Trades" to disabled.

**Comment by ncronin** [comment]
Is there an easy fix for this? It's a nice feature to have to give confirmation to traders who have donated to our bot.

Thanks!

**Comment by seishun** [comment]
I can't do anything about the mail confirmation. What I can do is pass the trade offer ID when trade_status is 6. I've never worked with trade offers so I have no idea if that's useful.

**Comment by Ax6** [comment]
Well, what I did to fix this is to interpretate the undefined (old library) result of 'end trade' as 'pending mail verification' so what happens next is an interval that checks if and when the trade offer containing the traded items has been accepted. At this point a 'end trade' is manually emitted passing a 'complete' status so that everything gets ported to the old software.

Maybe passing the trade offer id would be useful because you could then skip the part of checking the items and just track the status of that offer, although that would mean mixing the two libraries, i guess? I'm not sure if that would be a good thing

**Comment by seishun** [comment]
>if and when the trade offer containing the traded items has been accepted

Just curious, how do you find out which trade offer is the right one?

**Comment by Ax6** [comment]
I find the trade offer by getting the assets and comparing them with the items traded manually. Because of course only the partnerid wouldn't be enough to make sure it's right.

**Comment by jmate0321** [comment]
Even if you accept the trade offer, it's not 100% guaranteed that you are going to get the actual list of the new items. Trade offers are still unstable, and sometimes you don't get the tradeid attribute - as most of you already know. Is there any point to  mix the two libraries?

**Comment by seishun** [comment]
>and sometimes you don't get the tradeid attribute

Can you give some more information about this tradeid attribute?

**Comment by jmate0321** [comment]
You know that it's needed to load the list of the received items:
http://steamcommunity.com/trade/' + body.tradeid + '/receipt/

For some bots it's crucial to get this list, because of the new item ID's are rendered to the corresponding items there.

But again, the Steam tradeoffers are incredibly random. Sometimes, when you accept a trade offer you get an error message, instead of getting the actual tradeid as result. Of course, the offer actually gets accepted, but there is no way (to my knowledge) to get this tradeid ever again.

I cannot supply you proof right now, most of this comes from my tests, but I've seen lots of reports earlier regarding the same issue.

Maybe there is some other way to get the list of the new items somehow?

**Comment by Ax6** [comment]
I don't think there is any need of getting the list of the new items. Once you linked the trade offer id with the manual trade you just keep track of the offer status using the trade offer api.

Linking can be done by storing an array containing the ids of the item traded manually (which are given when 'onready' event occurs) and comparing them with the trade offers listed from the api.

**Comment by jmate0321** [comment]
Then how will you actually get the new item IDs without making big compromises?

You are right by the way, some bots don't have to actually be this precise. But as I mentioned earlier, there are some bots what really have to know every detail. We cannot just forget about this.

**Comment by Ax6** [comment]
Well I guess you can just refresh your backpack after the trade and get the id using the original_id, having the items ids right after the trade goes a bit off the actual purpose of those libraries I think.

**Comment by jmate0321** [comment]
Yeah could be done by using the public API only, because the JSON backpack doesn't actually contain the original_id attributes. But again, this creates a whole lot of other problems, eg there is no API for Steam inventories right now if I recall correctly. Also there were some more issues when I was trying test this.

Anyways, this converstation has became off-topic, so I will just stop complaining.

**Comment by ncronin** [comment]
Just out of curiosity, would (This)[https://github.com/Alex7Kom/node-steam-tradeoffers] implemented in work some how? As all trades, included manual trades, seem to be handled as trade offers now.

Not 100% sure if this would work, though.

**Comment by seishun** [comment]
I've committed a "fix" that emits the trade result properly and also passes the trade offer ID. I don't think there is anything else I can do within the scope of this library.
